#BSUB-J {{ job_name }}                  # name of the job / array jobs
#BSUB-g {{ job_group | /rzmq }}         # group the job belongs to
#BSUB-o {{ log_file | /dev/null }}      # stdout + stderr
#BSUB-M {{ memory | 4096 }}             # Memory requirements in Mbytes
#BSUB-R rusage[mem={{ memory | 4096 }}] # Memory requirements in Mbytes
#BSUB-q medium                          # name of the queue

R --no-save --no-restore -e \
    'clustermq:::worker("{{ job_name }}", "{{ master }}", {{ memory }})'
